//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_ProyectoClase.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosOferta
    {
        public long Id { get; set; }
        public long IdUsuario { get; set; }
        public long IdOferta { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Estado { get; set; }
    
        public virtual Oferta Oferta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
